name: Cross-Browser Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox] # Probar en múltiples navegadores

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Install ChromeDriver
        if: matrix.browser == 'chrome'
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Install GeckoDriver
        if: matrix.browser == 'firefox'
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver
          export PATH=$PATH:/usr/bin/

      - name: Build and Test
        run: mvn clean test -Dbrowser=${{ matrix.browser }}
