name: Cross-Browser Testing

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        if: matrix.browser == 'chrome'
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: Set Chrome Environment Variables
        if: matrix.browser == 'chrome'
        run: |
          echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=${{ steps.setup-chrome.outputs.chromedriver-path }}" >> $GITHUB_ENV

      - name: Install geckodriver
        if: matrix.browser == 'firefox'
        run: |
          wget -q "https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz" -O geckodriver.tar.gz
          tar -xvzf geckodriver.tar.gz -C /usr/local/bin
          rm geckodriver.tar.gz
          echo "GECKODRIVER_PATH=/usr/local/bin/geckodriver" >> $GITHUB_ENV

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest'

      - name: Set Firefox Environment Variables
        if: matrix.browser == 'firefox'
        run: |
          echo "FIREFOX_PATH=${{ steps.setup-firefox.outputs.firefox-path }}" >> $GITHUB_ENV

      - name: Build and Test
        run: |
          echo "CHROME_PATH=$CHROME_PATH"
          echo "CHROMEDRIVER_PATH=$CHROMEDRIVER_PATH"
          echo "FIREFOX_PATH=$FIREFOX_PATH"
          echo "GECKODRIVER_PATH=$GECKODRIVER_PATH"
          mvn clean test \
          -Dbrowser=${{ matrix.browser }} \
          -DchromePath=$CHROME_PATH \
          -DchromeDriverPath=$CHROMEDRIVER_PATH \
          -DfirefoxPath=$FIREFOX_PATH \
          -DfirefoxDriverPath=$GECKODRIVER_PATH
