name: Cross-Browser Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Chrome Setup
      - name: Verify ChromeDriver
        if: matrix.browser == 'chrome'
        run: |
          if ! command -v google-chrome &> /dev/null; then
            sudo apt-get install -y google-chrome-stable
          fi
          CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //;s/ .*//')
          DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      # Firefox Setup
      - name: Verify GeckoDriver
        if: matrix.browser == 'firefox'
        run: |
          if ! command -v firefox &> /dev/null; then
            sudo add-apt-repository -y ppa:mozillateam/ppa
            sudo apt-get update
            sudo apt-get install -y firefox
          fi
          wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.35.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Build and Test
        run: mvn clean test -Dbrowser=${{ matrix.browser }}
