name: Cross-Browser Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Chromium
        if: matrix.browser == 'chrome'
        run: |
          if ! command -v chromium-browser &> /dev/null; then
            sudo apt-get install -y chromium-browser --no-install-recommends
          fi
          DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Install GeckoDriver
        if: matrix.browser == 'firefox'
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.35.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Install Firefox
        if: matrix.browser == 'firefox'
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: *' | sudo tee /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin: release o=LP-PPA-mozillateam' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin-Priority: 501' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Build and Test
        run: mvn clean test -Dbrowser=${{ matrix.browser }}
