name: Cross-Browser Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        if: matrix.browser == 'chrome'
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: Set Chrome Environment Variables
        if: matrix.browser == 'chrome'
        run: |
          echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          echo "CHROME_VERSION=${{ steps.setup-chrome.outputs.chrome-version }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=${{ steps.setup-chrome.outputs.chromedriver-path }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_VERSION=${{ steps.setup-chrome.outputs.chromedriver-version }}" >> $GITHUB_ENV

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest'

      - name: Set Firefox Environment Variables
        if: matrix.browser == 'firefox'
        run: |
          echo "FIREFOX_PATH=${{ steps.setup-firefox.outputs.firefox-path }}" >> $GITHUB_ENV
          echo "FIREFOX_VERSION=${{ steps.setup-firefox.outputs.firefox-version }}" >> $GITHUB_ENV

      - name: Download geckodriver
        run: |
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz" -O geckodriver.tar.gz
          tar -xzf geckodriver.tar.gz -C /usr/local/bin
          rm geckodriver.tar.gz

      - name: Build and Test
        run: |
          mvn clean test \
          -Dbrowser=${{ matrix.browser }} \
          -DchromePath=$CHROME_PATH \
          -DchromeDriverPath=$CHROMEDRIVER_PATH \
          -DfirefoxPath=$FIREFOX_PATH
